FROM canpacis/pacis:latest

# Set working directory
WORKDIR /app

# Copy the source code
COPY . .

ENV PATH="/usr/local/bin:${PATH}"

# Install dependencies and build
RUN pcpg i
RUN pcpg c www
RUN go build -o pacis-www ./www

EXPOSE 8080

CMD ["./pacis-www"]