FROM canpacis/pacis:0.0.1

# Set working directory
WORKDIR /app

# Copy the source code
COPY . .

# Install dependencies and build
RUN /usr/local/bin/pcpg i
RUN /usr/local/bin/pcpg c www
RUN go build -o pacis-www ./www

ENV PATH="/app/bin:${PATH}"

EXPOSE 8080

CMD ["./pacis-www"]