# https://taskfile.dev

version: '3'

tasks:
  build-ui:
    cmds:
      - go generate ui/icons/icon.go
      - npx @tailwindcss/cli -i ./ui/components/public/input.css -o ./ui/components/public/main.css
