version: '3'

tasks:
  build-tailwind:
    cmds:
      - npx tailwindcss -i ./ui/input.css -o ./ui/static/output.css --minify
  dev-tailwind:
    cmds:
      - npx tailwindcss -i ./ui/input.css -o ./ui/static/output.css
  generate-templ:
    cmds:
      - templ generate
  dev:
    cmds:
      - task dev-tailwind
      - task generate-templ
      - go build -o ./test/tmp/main ./test/main.go
      - go build -o ./docs/tmp/main ./docs/main.go