# https://taskfile.dev

version: "3"

tasks:
  build-ui-assets:
    cmds:
      - npx @tailwindcss/cli -i ./ui/components/src/main.css -o ./ui/components/dist/main.css
      - esbuild ui/components/src/main.ts --bundle --outfile=./ui/components/dist/main.js --minify --sourcemap
  build-ui-icons:
    cmds:
      - go generate ui/icons/icon.go
  build-ui:
    cmds:
      - task build-ui-icons
      - task build-ui-assets
  build-base-docker:
    cmds:
      - docker build -t canpacis/pacis:0.0.1 -f Dockerfile.base .
      - docker push canpacis/pacis
  build-www-docker:
    cmds:
      - docker build -t canpacis/pacis-www -f Dockerfile.www .
      - docker push canpacis/pacis-www
