version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - task generate_icons
      - bun run registry:build --output registry/cmd/public/ui
      - cp ./registry.json ./registry/cmd/public/ui/registry.json
  generate_icons:
    cmd: go run lucide/cmd/generator.go -package lucide -out lucide ./lucide/module/icons
  run:
    cmd: go run ./registry/cmd
