version: "3"

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - bun run registry:build --output cmd/registry/public/ui
      - cp ./registry.json ./cmd/registry/public/ui/registry.json
  run:
    cmd: go run ./cmd/registry
