version: "3"

vars:
  GREETING: Hello, World!

tasks:
  generate_icons:
    cmd: go run lucide/cmd/pcicon.go -package lucide -out lucide ./lucide/module/icons
  build_registry:
    cmds:
      - task generate_icons
      - bun run registry:build --output registry/cmd/public/ui
      - cp ./registry.json ./registry/cmd/public/ui/registry.json
  run_registry:
    cmd: go run ./registry/cmd/main.go
