package renderer

// Elements

func Html(constituents ...Renderer) *Element       { return El("html", constituents...) }
func Body(constituents ...Renderer) *Element       { return El("body", constituents...) }
func Title(constituents ...Renderer) *Element      { return El("title", constituents...) }
func Style(constituents ...Renderer) *Element      { return El("style", constituents...) }
func Header(constituents ...Renderer) *Element     { return El("header", constituents...) }
func Main(constituents ...Renderer) *Element       { return El("main", constituents...) }
func Article(constituents ...Renderer) *Element    { return El("article", constituents...) }
func P(constituents ...Renderer) *Element          { return El("p", constituents...) }
func Div(constituents ...Renderer) *Element        { return El("div", constituents...) }
func Blockquote(constituents ...Renderer) *Element { return El("blockquote", constituents...) }
func Ul(constituents ...Renderer) *Element         { return El("ul", constituents...) }
func Li(constituents ...Renderer) *Element         { return El("li", constituents...) }
func Dd(constituents ...Renderer) *Element         { return El("dd", constituents...) }
func A(constituents ...Renderer) *Element          { return El("a", constituents...) }
func Strong(constituents ...Renderer) *Element     { return El("strong", constituents...) }
func U(constituents ...Renderer) *Element          { return El("u", constituents...) }
func Ins(constituents ...Renderer) *Element        { return El("ins", constituents...) }
func Small(constituents ...Renderer) *Element      { return El("small", constituents...) }
func Sub(constituents ...Renderer) *Element        { return El("sub", constituents...) }
func Code(constituents ...Renderer) *Element       { return El("code", constituents...) }
func Samp(constituents ...Renderer) *Element       { return El("samp", constituents...) }
func Q(constituents ...Renderer) *Element          { return El("q", constituents...) }
func Rt(constituents ...Renderer) *Element         { return El("rt", constituents...) }
func Br(constituents ...Renderer) *Element         { return El("br", constituents...) }
func Bdi(constituents ...Renderer) *Element        { return El("bdi", constituents...) }
func Caption(constituents ...Renderer) *Element    { return El("caption", constituents...) }
func Td(constituents ...Renderer) *Element         { return El("td", constituents...) }
func Thead(constituents ...Renderer) *Element      { return El("thead", constituents...) }
func Tbody(constituents ...Renderer) *Element      { return El("tbody", constituents...) }
func Col(constituents ...Renderer) *Element        { return El("col", constituents...) }
func Picture(constituents ...Renderer) *Element    { return El("picture", constituents...) }
func Figcaption(constituents ...Renderer) *Element { return El("figcaption", constituents...) }
func Video(constituents ...Renderer) *Element      { return El("video", constituents...) }
func Track(constituents ...Renderer) *Element      { return El("track", constituents...) }
func Object(constituents ...Renderer) *Element     { return El("object", constituents...) }
func Iframe(constituents ...Renderer) *Element     { return El("iframe", constituents...) }
func Abbr(constituents ...Renderer) *Element       { return El("abbr", constituents...) }
func Meter(constituents ...Renderer) *Element      { return El("meter", constituents...) }
func Form(constituents ...Renderer) *Element       { return El("form", constituents...) }
func Input(constituents ...Renderer) *Element      { return El("input", constituents...) }
func Select(constituents ...Renderer) *Element     { return El("select", constituents...) }
func Option(constituents ...Renderer) *Element     { return El("option", constituents...) }
func Label(constituents ...Renderer) *Element      { return El("label", constituents...) }
func Datalist(constituents ...Renderer) *Element   { return El("datalist", constituents...) }
func Output(constituents ...Renderer) *Element     { return El("output", constituents...) }
func Command(constituents ...Renderer) *Element    { return El("command", constituents...) }
func Basefont(constituents ...Renderer) *Element   { return El("basefont", constituents...) }
func Center(constituents ...Renderer) *Element     { return El("center", constituents...) }
func Font(constituents ...Renderer) *Element       { return El("font", constituents...) }
func Frameset(constituents ...Renderer) *Element   { return El("frameset", constituents...) }
func Strike(constituents ...Renderer) *Element     { return El("strike", constituents...) }
func Btn(constituents ...Renderer) *Element        { return El("button", constituents...) }
func H1(constituents ...Renderer) *Element         { return El("h1", constituents...) }
func H2(constituents ...Renderer) *Element         { return El("h2", constituents...) }
func H3(constituents ...Renderer) *Element         { return El("h3", constituents...) }
func H4(constituents ...Renderer) *Element         { return El("h4", constituents...) }
func H5(constituents ...Renderer) *Element         { return El("h5", constituents...) }
func H6(constituents ...Renderer) *Element         { return El("h6", constituents...) }
func Pre(constituents ...Renderer) *Element        { return El("pre", constituents...) }
func Hr(constituents ...Renderer) *Element         { return El("hr", constituents...) }
func Ol(constituents ...Renderer) *Element         { return El("ol", constituents...) }
func Dt(constituents ...Renderer) *Element         { return El("dt", constituents...) }
func Span(constituents ...Renderer) *Element       { return El("span", constituents...) }
func Em(constituents ...Renderer) *Element         { return El("em", constituents...) }
func B(constituents ...Renderer) *Element          { return El("b", constituents...) }
func S(constituents ...Renderer) *Element          { return El("s", constituents...) }
func Mark(constituents ...Renderer) *Element       { return El("mark", constituents...) }
func Sup(constituents ...Renderer) *Element        { return El("sup", constituents...) }
func Dfn(constituents ...Renderer) *Element        { return El("dfn", constituents...) }
func Var(constituents ...Renderer) *Element        { return El("var", constituents...) }
func Kbd(constituents ...Renderer) *Element        { return El("kbd", constituents...) }
func Cite(constituents ...Renderer) *Element       { return El("cite", constituents...) }
func Ruby(constituents ...Renderer) *Element       { return El("ruby", constituents...) }
func Rp(constituents ...Renderer) *Element         { return El("rp", constituents...) }
func Wbr(constituents ...Renderer) *Element        { return El("wbr", constituents...) }
func Bdo(constituents ...Renderer) *Element        { return El("bdo", constituents...) }
func Table(constituents ...Renderer) *Element      { return El("table", constituents...) }
func Tr(constituents ...Renderer) *Element         { return El("tr", constituents...) }
func Th(constituents ...Renderer) *Element         { return El("th", constituents...) }
func Tfoot(constituents ...Renderer) *Element      { return El("tfoot", constituents...) }
func Colgroup(constituents ...Renderer) *Element   { return El("colgroup", constituents...) }
func Img(constituents ...Renderer) *Element        { return El("img", constituents...) }
func Figure(constituents ...Renderer) *Element     { return El("figure", constituents...) }
func Map(constituents ...Renderer) *Element        { return El("map", constituents...) }
func Area(constituents ...Renderer) *Element       { return El("area", constituents...) }
func Audio(constituents ...Renderer) *Element      { return El("audio", constituents...) }
func Source(constituents ...Renderer) *Element     { return El("source", constituents...) }
func Script(constituents ...Renderer) *Element     { return El("script", constituents...) }
func Noscript(constituents ...Renderer) *Element   { return El("noscript", constituents...) }
func Param(constituents ...Renderer) *Element      { return El("param", constituents...) }
func Embed(constituents ...Renderer) *Element      { return El("embed", constituents...) }
func Canvas(constituents ...Renderer) *Element     { return El("canvas", constituents...) }
func Address(constituents ...Renderer) *Element    { return El("address", constituents...) }
func Progress(constituents ...Renderer) *Element   { return El("progress", constituents...) }

// Attributes

func Accept(value string) *HtmlAttribute          { return Attr("accept", value) }
func AcceptCharset(value string) *HtmlAttribute   { return Attr("accept-charset", value) }
func AccessKey(value string) *HtmlAttribute       { return Attr("accesskey", value) }
func Action(value string) *HtmlAttribute          { return Attr("action", value) }
func Align(value string) *HtmlAttribute           { return Attr("align", value) }
func Alt(value string) *HtmlAttribute             { return Attr("alt", value) }
func Async(value string) *HtmlAttribute           { return Attr("async", value) }
func Autocomplete(value string) *HtmlAttribute    { return Attr("autocomplete", value) }
func Autofocus(value string) *HtmlAttribute       { return Attr("autofocus", value) }
func Autoplay(value string) *HtmlAttribute        { return Attr("autoplay", value) }
func BGColor(value string) *HtmlAttribute         { return Attr("bgcolor", value) }
func Border(value string) *HtmlAttribute          { return Attr("border", value) }
func Charset(value string) *HtmlAttribute         { return Attr("charset", value) }
func Checked(value string) *HtmlAttribute         { return Attr("checked", value) }
func CiteAttr(value string) *HtmlAttribute        { return Attr("cite", value) }
func Class(value string) *HtmlAttribute           { return Attr("class", value) }
func Color(value string) *HtmlAttribute           { return Attr("color", value) }
func Cols(value string) *HtmlAttribute            { return Attr("cols", value) }
func Colspan(value string) *HtmlAttribute         { return Attr("colspan", value) }
func Content(value string) *HtmlAttribute         { return Attr("content", value) }
func ContentEditable(value string) *HtmlAttribute { return Attr("contenteditable", value) }
func Controls(value string) *HtmlAttribute        { return Attr("controls", value) }
func Coords(value string) *HtmlAttribute          { return Attr("coords", value) }
func Data(name, value string) *HtmlAttribute      { return Attr("data-"+name, value) }
func Datetime(value string) *HtmlAttribute        { return Attr("datetime", value) }
func Default(value string) *HtmlAttribute         { return Attr("default", value) }
func Defer(value string) *HtmlAttribute           { return Attr("defer", value) }
func Dir(value string) *HtmlAttribute             { return Attr("dir", value) }
func Dirname(value string) *HtmlAttribute         { return Attr("dirname", value) }
func Disabled(value string) *HtmlAttribute        { return Attr("disabled", value) }
func Download(value string) *HtmlAttribute        { return Attr("download", value) }
func Draggable(value string) *HtmlAttribute       { return Attr("draggable", value) }
func Enctype(value string) *HtmlAttribute         { return Attr("enctype", value) }
func EnterKeyHint(value string) *HtmlAttribute    { return Attr("enterkeyhint", value) }
func For(value string) *HtmlAttribute             { return Attr("for", value) }
func FormAttr(value string) *HtmlAttribute        { return Attr("form", value) }
func FormAction(value string) *HtmlAttribute      { return Attr("formaction", value) }
func Headers(value string) *HtmlAttribute         { return Attr("headers", value) }
func Height(value string) *HtmlAttribute          { return Attr("height", value) }
func Hidden(value string) *HtmlAttribute          { return Attr("hidden", value) }
func High(value string) *HtmlAttribute            { return Attr("high", value) }
func Href(value string) *HtmlAttribute            { return Attr("href", value) }
func HrefLang(value string) *HtmlAttribute        { return Attr("hreflang", value) }
func HttpEquiv(value string) *HtmlAttribute       { return Attr("http-equiv", value) }
func ID(value string) *HtmlAttribute              { return Attr("id", value) }
func Inert(value string) *HtmlAttribute           { return Attr("inert", value) }
func InputMode(value string) *HtmlAttribute       { return Attr("inputmode", value) }
func IsMap(value string) *HtmlAttribute           { return Attr("ismap", value) }
func Kind(value string) *HtmlAttribute            { return Attr("kind", value) }
func LabelAttr(value string) *HtmlAttribute       { return Attr("label", value) }
func Src(value string) *HtmlAttribute             { return Attr("src", value) }
func Role(value string) *HtmlAttribute            { return Attr("role", value) }
func Lang(value string) *HtmlAttribute            { return Attr("lang", value) }
func List(value string) *HtmlAttribute            { return Attr("list", value) }
func Loop(value string) *HtmlAttribute            { return Attr("loop", value) }
func Low(value string) *HtmlAttribute             { return Attr("low", value) }
func Max(value string) *HtmlAttribute             { return Attr("max", value) }
func MaxLength(value string) *HtmlAttribute       { return Attr("maxlength", value) }
func Media(value string) *HtmlAttribute           { return Attr("media", value) }
func Method(value string) *HtmlAttribute          { return Attr("method", value) }
func Min(value string) *HtmlAttribute             { return Attr("min", value) }
func Multiple(value string) *HtmlAttribute        { return Attr("multiple", value) }
func Muted(value string) *HtmlAttribute           { return Attr("muted", value) }
func Name(value string) *HtmlAttribute            { return Attr("name", value) }
func NoValidate(value string) *HtmlAttribute      { return Attr("novalidate", value) }
