// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package test

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	ui "github.com/CanPacis/pacis/ui"
)

func avatarSizeTest() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeHuge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeLarge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Img("/public/11.jpg").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeSmall).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeTiny).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func avatarWithoutImageTest() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Jodie Whittaker").Variant(ui.SizeHuge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Peter Capaldi").Variant(ui.SizeLarge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("David Tennant").Variant(ui.SizeSmall).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Christopher Eccleston").Variant(ui.SizeTiny).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func avatarWithTooltipsTest() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Jodie Whittaker").Tooltip().Variant(ui.SizeHuge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Peter Capaldi").Tooltip().Variant(ui.SizeLarge).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Matt Smith").Tooltip().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("David Tennant").Tooltip().Variant(ui.SizeSmall).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Avatar("Christopher Eccleston").Tooltip().Variant(ui.SizeTiny).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func avatarGroupTest() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-wrap items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp").Variant(ui.SizeHuge),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif").Variant(ui.SizeHuge),
			ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeHuge),
			ui.Avatar("David Tennant").Img("/public/10.jpg").Variant(ui.SizeHuge),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg").Variant(ui.SizeHuge),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp").Variant(ui.SizeLarge),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif").Variant(ui.SizeLarge),
			ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeLarge),
			ui.Avatar("David Tennant").Img("/public/10.jpg").Variant(ui.SizeLarge),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg").Variant(ui.SizeLarge),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp"),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif"),
			ui.Avatar("Matt Smith").Img("/public/11.jpg"),
			ui.Avatar("David Tennant").Img("/public/10.jpg"),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg"),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp").Variant(ui.SizeSmall),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif").Variant(ui.SizeSmall),
			ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeSmall),
			ui.Avatar("David Tennant").Img("/public/10.jpg").Variant(ui.SizeSmall),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg").Variant(ui.SizeSmall),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp").Variant(ui.SizeTiny),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif").Variant(ui.SizeTiny),
			ui.Avatar("Matt Smith").Img("/public/11.jpg").Variant(ui.SizeTiny),
			ui.Avatar("David Tennant").Img("/public/10.jpg").Variant(ui.SizeTiny),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg").Variant(ui.SizeTiny),
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func avatarGroupOverflowTest() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-wrap items-center gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Img("/public/13.webp"),
			ui.Avatar("Peter Capaldi").Img("/public/12.avif"),
			ui.Avatar("Matt Smith").Img("/public/11.jpg"),
			ui.Avatar("David Tennant").Img("/public/10.jpg"),
			ui.Avatar("Christopher Eccleston").Img("/public/9.jpg"),
		).Max(3).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.AvatarGroup(
			ui.Avatar("Jodie Whittaker").Tooltip().Img("/public/13.webp"),
			ui.Avatar("Peter Capaldi").Tooltip().Img("/public/12.avif"),
			ui.Avatar("Matt Smith").Tooltip().Img("/public/11.jpg"),
			ui.Avatar("David Tennant").Tooltip().Img("/public/10.jpg"),
			ui.Avatar("Christopher Eccleston").Tooltip().Img("/public/9.jpg"),
		).Max(3).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func init() {
	page := NewTestPage(UITestPage, "Avatar", "An avatar is a graphical representation, often a circular image or icon, used to visually identify a user or profile in a user interface.", "avatar")
	page.Define("Avatar Size", avatarSizeTest())
	page.Define("Avatar Without Image", avatarWithoutImageTest())
	page.Define("Avatar With Tooltips", avatarWithTooltipsTest())
	page.Define("Avatar Group", avatarGroupTest())
	page.Define("Avatar Group Overflow", avatarGroupOverflowTest())
	RegisterPage(page)
}
